# Compose file for local Jenkins deployment with defaults on Docker,
# for test purpose only!
services:
  jenkins:
    image: jenkins:v1
    hostname: jenkins
    privileged: true
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4096M
        reservations:
          memory: 2048M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_data:
    name: jenkins_data
    driver: local
